### ISSUE TITLE
clojure.lang.ArityException: Wrong number of args (2) passed to: promesa.core/all

### ISSUE THREAD

**Issue by xiexed** [funcool/promesa#75]
A sample with `plet` from docs doesn't work in `[funcool/promesa "4.0.2"]`

the following code:

```
(ns clojure-sample.core
  (:require [promesa.core :as p]))


@(p/plet [a (p/delay 100 1)
         b (p/delay 200 2)
         c (p/delay 120 3)]
        (+ a b c))

```

fails:

```
Exception in thread "main" Syntax error compiling at (/Users/nicolay.mitropolsky/IdeaProjects/clojure-sample/src/clojure_sample/core.clj:5:1).
	at clojure.lang.Compiler.load(Compiler.java:7647)
	at clojure.lang.Compiler.loadFile(Compiler.java:7573)
	at clojure.main$load_script.invokeStatic(main.clj:452)
	at clojure.main$script_opt.invokeStatic(main.clj:512)
	at clojure.main$script_opt.invoke(main.clj:507)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
Caused by: java.util.concurrent.ExecutionException: clojure.lang.ArityException: Wrong number of args (2) passed to: promesa.core/all
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at clojure.core$deref_future.invokeStatic(core.clj:2300)
	at clojure.core$deref.invokeStatic(core.clj:2320)
	at clojure.core$deref.invoke(core.clj:2306)
	at clojure_sample.core$eval892.invokeStatic(core.clj:0)
	at clojure_sample.core$eval892.invoke(core.clj)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	... 9 more
Caused by: clojure.lang.ArityException: Wrong number of args (2) passed to: promesa.core/all
	at clojure.lang.AFn.throwArity(AFn.java:429)
	at clojure.lang.AFn.invoke(AFn.java:36)
	at clojure_sample.core$eval892$fn__893.invoke(core.clj:5)
	at clojure.core$comp$fn__5792.invoke(core.clj:2569)
	at promesa.util.FunctionWrapper.apply(util.cljc:43)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:143)
	at promesa.impl$eval649$fn__652.invoke(impl.cljc:120)
	at promesa.protocols$eval177$fn__199$G__162__212.invoke(protocols.cljc:28)
	at promesa.impl$eval675$fn__678.invoke(impl.cljc:177)
	at promesa.protocols$eval177$fn__199$G__162__212.invoke(protocols.cljc:28)
	at promesa.core$then.invokeStatic(core.cljc:152)
	at promesa.core$then.invoke(core.cljc:142)
	at promesa.core$bind.invokeStatic(core.cljc:169)
	at promesa.core$bind.invoke(core.cljc:167)
	at clojure_sample.core$eval892.invokeStatic(core.clj:5)
	... 12 more
```

**Comment by niwinz** [comment]
Fixed in `5.0.0-SNAPSHOT`
